[package]
name = "jikken"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
hyper = { version = "0.14.19", features = ["full"] }
hyper-tls = { version = "0.5.0" }
tokio = { version = "1", features = ["full"] }
walkdir = { version = "2" }
toml = { version = "0.5.9" }
serde = { version = "1.0", features = ["derive"] }
indicatif = {version = "*", features = ["rayon"]}