[package]
name = "jk"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
hyper-tls = { version = "0.5" }
tokio = { version = "1.23", features = ["full"] }
walkdir = { version = "2.3" }
toml = { version = "0.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_yaml = { version = "0.9" }
indicatif = {version = "*", features = ["rayon"]}
exitcode = {version = "1.1"}
chrono = {version = "0.4"}
log = {version = "0.4", features = ["std"]}
clap = { version = "4.0", features = ["derive"] }