[package]
name = "jikken"
version = "0.2.0"
edition = "2021"
authors = ["Louis Russo <louis@jikken.io>"]
description = """
jikken is a cli tool for automated API testing. it recursively
searches directories for JKT files (Jikken Test Definitions)
which will execute jobs for testing APIs.
it has first class support on Windows, macOS, and Linux.
"""
documentation = "https://github.com/jikkenio/jikken"
homepage = "https://github.com/jikkenio/jikken"
repository = "https://github.com/jikkenio/jikken"
keywords = ["test", "testing", "api", "tool"]
categories = ["command-line-utilities", "development-tools"]
license = "MIT"

[[bin]]
name = "jk"
path = "src/main.rs"
bench = false

[dependencies]
hyper = { version = "0.14", features = ["full"] }
hyper-tls = { version = "0.5" }
tokio = { version = "1.23", features = ["full"] }
walkdir = { version = "2.3" }
toml = { version = "0.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_yaml = { version = "0.9" }
indicatif = {version = "0.17", features = ["rayon"] }
exitcode = {version = "1.1" }
chrono = {version = "0.4" }
log = {version = "0.4", features = ["std"] }
clap = { version = "4.0", features = ["derive"] }
assert-json-diff = { version = "2.0" }
url = { version = "2.3" }
